spring.application.name=order-service

server.port=8083

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info

catalogue.service.url=http://localhost:8081